### PR TITLE
FLUID-4755 and FLUID-4514

### PR DESCRIPTION
**Pull request by colinbdclark**
This pull requests contains semi-tested fixes for FLUID-4755 (the nightly Builder is broken) and FLUID-4514 (Link to the Builder on the Builder is broken).

From my tests, this pull request fixes both issues. However, due to problems with the Builder's deploy scripts apparently not working with my version of MAMP/MySQL, I haven't been able to try it out with a fully-functioning local instance of the Builder.

I'm hoping perhaps someone is set up to test this for me fully. If not, since the Builder is already completely borked, I can't see that there's any harm in pushing this after a thorough code review.

@cindyli or @jobara, do you have a moment to take a look?

### CODE REVIEW

**Comment by cindyli** [comment]
Tested with my local builder setup. The pull request does fix 4755 & 4514, although the download click throws error which is from the problem with running ant build via php exec function. Pretty certain the changes made here won't cause that error. Very likely it's just related to my local settings since this is the first time I run builder with the new Mac.

It should be safe to merge this pull request.

**Comment by jobara** [comment]
@colinbdclark maybe now would be a good time to switch the builder to use a built version of Infusion instead of linking to the individual files.

**Comment by colinbdclark** [comment]
I filed a JIRA for this issue, @jobara:

http://issues.fluidproject.org/browse/FLUID-4757

I think it's worth getting a temporary fix in now, and address this as part of a larger refactoring of the Builder. What do you think?

**Comment by jobara** [comment]
now that there is a specific jira for this issue, the pull request looks good.
http://issues.fluidproject.org/browse/FLUID-4757

**Pull request merged**
